/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 TQ3180NE_Base.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/TQ3180NE_Base.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1.57, -0.68]} scale={0.001}>
        <mesh geometry={nodes.Mesh016.geometry} material={materials['M_Buildings.004']} />
        <mesh geometry={nodes.Mesh016_1.geometry} material={materials['M_Bridges.004']} />
        <mesh geometry={nodes.Mesh016_2.geometry} material={materials['M_Terrain.004']} />
        <mesh geometry={nodes.Mesh016_3.geometry} material={materials.M_Rails} />
        <mesh geometry={nodes.Mesh016_4.geometry} material={materials['M_Roads.004']} />
        <mesh geometry={nodes.Mesh016_5.geometry} material={materials['M_Greenspace.004']} />
        <mesh geometry={nodes.Mesh016_6.geometry} material={materials['M_Construction.003']} />
        <mesh geometry={nodes.Mesh016_7.geometry} material={materials['M_Water.003']} />
        <mesh geometry={nodes.Mesh016_8.geometry} material={materials['M_TreeBark.004']} />
        <mesh geometry={nodes.Mesh016_9.geometry} material={materials['M_TreeLeaves.004']} />
      </group>
      <mesh geometry={nodes.Base.geometry} material={materials['Material.003']} scale={[25.24, 1.01, 25.24]} />
    </group>
  )
}

useGLTF.preload('/TQ3180NE_Base.gltf')
