/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 TQ3281SW_Base.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/TQ3281SW_Base.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 4.04, 0]} scale={0.001}>
        <mesh geometry={nodes.Mesh010.geometry} material={materials.M_TreeBark} />
        <mesh geometry={nodes.Mesh010_1.geometry} material={materials.M_TreeLeaves} />
        <mesh geometry={nodes.Mesh010_2.geometry} material={materials.M_Bridges} />
        <mesh geometry={nodes.Mesh010_3.geometry} material={materials.M_Water} />
        <mesh geometry={nodes.Mesh010_4.geometry} material={materials.M_Terrain} />
        <mesh geometry={nodes.Mesh010_5.geometry} material={materials.M_Roads} />
        <mesh geometry={nodes.Mesh010_6.geometry} material={materials.M_Construction} />
        <mesh geometry={nodes.Mesh010_7.geometry} material={materials.M_Greenspace} />
        <mesh geometry={nodes.Mesh010_8.geometry} material={materials.M_Buildings} />
      </group>
      <mesh geometry={nodes.Base.geometry} material={materials['Material.003']} scale={[25.24, 1.01, 25.24]} />
    </group>
  )
}

useGLTF.preload('/TQ3281SW_Base.gltf')
