/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 TQ3381SW_Base.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/TQ3381SW_Base.gltf')
  return (
    <group {...props} dispose={null}>
      <group  scale={0.001}>
        <mesh geometry={nodes.Mesh005.geometry} material={materials.M_Terrain} />
        <mesh geometry={nodes.Mesh005_1.geometry} material={materials.M_Bridges} />
        <mesh geometry={nodes.Mesh005_2.geometry} material={materials.M_Greenspace} />
        <mesh geometry={nodes.Mesh005_3.geometry} material={materials.M_Roads} />
        <mesh geometry={nodes.Mesh005_4.geometry} material={materials.M_Buildings} />
      </group>
      <mesh geometry={nodes.Base.geometry} material={materials['Material.003']} scale={[25.24, 1.01, 25.24]} />
    </group>
  )
}

useGLTF.preload('/TQ3381SW_Base.gltf')
